# configuration settings

# example configuraiton:
#registries:
#  -
#    hostname: 'my-registry.com'
#    authConfig: 'username:password'
#    syncPeriod: '*/1 * * * *'
#    syncerScript: 'getImages.sh'
#    registryProvider: 'docker'
#
# ---
# syncer scripts should be placed in pkg/sync-scripts

registries:
  -
    hostname: 'haffel1.cp-dev.rancher.space'
    repository: ''
    pullAuthConfig: ''
    pushAuthConfig: ''
    syncPeriod: '*/1 * * * *'
    syncerScript: 'sync-scripts/get-rancher-images-for-tag'
    syncerScriptArgs: 'v2.6.4'
    deleteLocalImages: true


# display can be either 'spinner' or empty.
# spinner will display a spinner when syncing registries, but doesn't display output for multiple registries being sync'ed at the same time very well.
# use this if you're just loading images, or if you are only syncing registries on periods which will not overlap
#
# std will just display the raw output of the docker sdk, which is more verbose
display: "spinner"
api:
  port: 8001
  enabled: true
  authToken: this-is-a-token
  enableAuth: true