#!/bin/sh

TAG=v2.6.4

# echo "https://github.com/rancher/rancher/releases/download/$1/rancher-images.txt"

wget "https://github.com/rancher/rancher/releases/download/$1/rancher-images.txt" -q

cat rancher-images.txt